name: Mirror to personal repo

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal repo
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git remote add personal https://tomost-dada:${TOKEN}@github.com/tomost-dada/aaa-deploy.git
          git push personal main --force
